apiVersion: v1
kind: Service
metadata:
 labels:
   app: backend-BUILD_ID
 name: backend-BUILD_ID
spec:
 ports:
 - name: '3000'
   port: 3000
   targetPort: 3000
 selector:
   app: backend-BUILD_ID
 type: LoadBalancer #Allow external access