version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:

  install-backend-dependencies:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-install]
      - run:
          name: Back-end install
          command: |
             cd backend
             npm i
      - save_cache:
          paths: [backend/node_modules]
          key: backend-install

  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-install]
      - run:
          name: Scan Back-end
          command: |
            cd backend
            npm audit fix --audit-level=critical --force

  eslint-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-install]
      - run:
          name: ESLint Back-end
          command: |
            cd backend
            npm i -D
            npm run eslint

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-install]
      - run:
          name: Test Back-end
          command: |
            cd backend
            npm run test
      - save_cache:
          paths: [backend/node_modules]
          key: backend-install

  # build-and-push-docker:
  #   executor: docker/docker
  #   steps:
  #     - checkout
  #     - run:
  #         name: Get in dir
  #         command: |
  #           cd backend
  #     - docker/publish:
  #         image: fr3d3rico/udacity-web-app:latest

workflows:
  default:
    jobs:
      - install-backend-dependencies:
          filters:
            branches:
              only: [main]
      - scan-backend:
          requires: [install-backend-dependencies]
      - eslint-backend:
          requires: [scan-backend]
      - test-backend:
          requires: [eslint-backend]
      build-and-push-docker:
        requires: [test-backend]
        jobs:
          - docker/publish:
              image: fr3d3rico/udacity-web-app:latest
              update-description: false