version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:

  # install-backend-dependencies:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys: [backend-install]
  #     - run:
  #         name: Back-end install
  #         command: |
  #            cd backend
  #            npm i
  #     - save_cache:
  #         paths: [backend/node_modules]
  #         key: backend-install

  # scan-backend:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys: [backend-install]
  #     - run:
  #         name: Scan Back-end
  #         command: |
  #           cd backend
  #           npm audit fix --audit-level=critical --force

  # eslint-backend:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys: [backend-install]
  #     - run:
  #         name: ESLint Back-end
  #         command: |
  #           cd backend
  #           npm i -D
  #           npm run eslint

  # test-backend:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys: [backend-install]
  #     - run:
  #         name: Test Back-end
  #         command: |
  #           cd backend
  #           npm run test
  #     - save_cache:
  #         paths: [backend/node_modules]
  #         key: backend-install

  build-and-push-docker:
    docker:
      - image: circleci/golang:1.15
          auth:
            username: fr3d3rico
            password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Docker Build and Push
          command: |
            cd backend
            docker build -t udacity-web-app .
            docker tag udacity-web-app fr3d3rico/udacity-web-app:latest
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
            sudo docker push fr3d3rico/udacity-web-app:latest
      # - docker/check
      # - docker/build:
      #     image: fr3d3rico/udacity-web-app:latest
      # - docker/push:
      #     image: fr3d3rico/udacity-web-app:latest

workflows:
  default:
    jobs:
      # - install-backend-dependencies:
      #     filters:
      #       branches:
      #         only: [main]
      # - scan-backend:
      #     requires: [install-backend-dependencies]
      # - eslint-backend:
      #     requires: [scan-backend]
      # - test-backend:
      #     requires: [eslint-backend]
      - build-and-push-docker:
          # requires: [test-backend]